# Generated by Django 5.2.3 on 2025-06-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "price_with_discount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена со скидкой"
                    ),
                ),
                (
                    "rate",
                    models.IntegerField(blank=True, null=True, verbose_name="Рейтинг"),
                ),
                (
                    "review_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Количество отзывов"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
